server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              # true -> Gateway tự tạo route dựa trên service name từ Eureka
              # false -> tắt auto-routing -> tự định nghĩa routes
              enabled: false
          globalcors:
            cors-configurations:
              "[/**]":
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: false
          default-filters:
            # DedupeResponseHeader: fix CORS duplicate header (loại trùng) khi:
            #   + Gateway thêm header
            #   + Service cũng thêm header
            # -> bị duplicate -> browser chặn
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# resilience
resilience4j:
  circuitbreaker:
    instances:
      default-cb:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      default-cb:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, metrics
  endpoint:
    gateway:
      enabled: true
